spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/OsFacil}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:OSFACIL_LOCAL_DEV_ONLY_CHANGE_ME_2026_SUPER_SECRET_512_BITS_MINIMUM_LENGTH}
